version: '3'
services:
  chess-explorer:
    container_name: server
    restart: always
    build: .
    image: jlambert1/chess-explorer:latest
    ports:
      - '3001:3001'
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./.data:/data/db
    ports:
      - '27017:27017'
