name: Deploy App to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install --prefix app
          npm run build --prefix app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: app/build
